[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".output/server"

[build.environment]
  NITRO_PRESET = "netlify"

[dev]
  framework = "nuxt"

[functions]
  node_bundler = "esbuild"

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200