[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]