[build]
  command = "npm run build"
  publish = ".netlify/functions"
  functions = ".output/server"

[build.environment]
  NITRO_PRESET = "netlify"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]