[build]
  command = "npm run build"
  publish = ".output/public"

[dev]
  framework = "nuxt"

[functions]
  directory = ".output/server"
  node_bundler = "esbuild"

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]

[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200