[build]
  command = "npm run build"
  publish = "dist"
  functions = ".output/server"

[dev]
  framework = "nuxt"

[functions]
  node_bundler = "esbuild"

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200