[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "static"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://lh3.googleusercontent.com/.*","https://i.ibb.co/.*"]